# Generated by Django 4.0.5 on 2022-07-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canadiannutrientfile', '0002_nutrientname_nutrientsource_mesurename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_source', models.CharField(blank=True, max_length=300, null=True)),
                ('recipy_url', models.URLField(blank=True, max_length=250, null=True, unique=True)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('recipy_title', models.CharField(blank=True, max_length=100, null=True)),
                ('recipy_yield_str', models.CharField(blank=True, max_length=100, null=True)),
                ('recipy_yield_int', models.IntegerField(blank=True, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=100, null=True)),
                ('cook_time', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(max_length=500)),
                ('recipy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recipy')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_str', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canadiannutrientfile.conversionfactor')),
                ('food_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodname')),
                ('recipy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recipy')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250, unique=True)),
                ('recipy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recipy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('recipy', 'ingredient_str'), name='unique Ingredient'),
        ),
    ]
