# Generated by Django 4.0.5 on 2022-07-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canadiannutrientfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=6)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodname')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylist.grocerystore')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylist.groceryitems')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylist.groceryitemstatus')),
            ],
        ),
    ]
