# Generated by Django 4.0.5 on 2022-07-07 17:38

from django.db import migrations, models
import django.utils.timezone
import grocerylist.models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grocerystore',
            name='name',
            field=grocerylist.models.NameField(max_length=100, unique=True),
        ),
    ]
