# Generated by Django 4.0.5 on 2022-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_groceryitems_created_at_groceryitems_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitems',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groceryitems',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
