# Generated by Django 4.0.5 on 2022-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0004_alter_groceryitems_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitems',
            name='qty',
            field=models.CharField(max_length=10),
        ),
    ]
