# Generated by Django 4.0.5 on 2023-01-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0006_groceryitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitems',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
