# Generated by Django 4.0.5 on 2023-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0007_groceryitems_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='groceryitems',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
