# Generated by Django 4.0.5 on 2022-07-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depensesfilles', '0003_categorie_alter_depenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='desc',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
