# Generated by Django 4.0.5 on 2022-07-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depensesfilles', '0004_alter_categorie_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='description',
        ),
        migrations.AddField(
            model_name='depenses',
            name='categorie_1',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depenses',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depensesfilles.categorie'),
        ),
    ]
