# Generated by Django 4.0.5 on 2022-07-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depensesfilles', '0005_remove_depenses_description_depenses_categorie_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='categorie_1',
        ),
        migrations.AddField(
            model_name='depenses',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
