# Generated by Django 4.0.5 on 2022-07-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('food_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_group_code', models.IntegerField(unique=True)),
                ('food_group_name', models.CharField(max_length=255)),
                ('food_group_name_f', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('food_source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_source_code', models.IntegerField()),
                ('food_source_name', models.CharField(max_length=255)),
                ('food_source_name_f', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_code', models.IntegerField()),
                ('food_description', models.CharField(max_length=255)),
                ('food_description_f', models.CharField(max_length=255)),
                ('country_code', models.IntegerField()),
                ('food_date_of_entry', models.DateField(blank=True, null=True)),
                ('food_date_of_publication', models.DateField(blank=True, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodgroup')),
                ('food_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodsource')),
            ],
        ),
    ]
