# Generated by Django 4.0.5 on 2022-07-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canadiannutrientfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientName',
            fields=[
                ('nutrient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nutrient_code', models.IntegerField(unique=True)),
                ('nutrient_symbole', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=8)),
                ('nutrient_name', models.CharField(max_length=200)),
                ('nutrient_name_f', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=20)),
                ('nutrient_decimal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NutrientSource',
            fields=[
                ('nutrient_source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nutrient_source_code', models.IntegerField()),
                ('nutrient_source_description', models.CharField(max_length=200)),
                ('nutrient_source_description_f', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MesureName',
            fields=[
                ('mesure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mesure_name', models.CharField(max_length=200)),
                ('mesure_name_f', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('mesure_name', 'mesure_name_f')},
            },
        ),
        migrations.CreateModel(
            name='NutrientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('standard_error', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('number_of_observations', models.IntegerField(blank=True, null=True)),
                ('nutrient_date_of_entry', models.DateField(blank=True, null=True)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodname')),
                ('nutrient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.nutrientname')),
                ('nutrient_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.nutrientsource')),
            ],
            options={
                'unique_together': {('food_name', 'nutrient_name', 'nutrient_value')},
            },
        ),
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor_value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('conversion_date_of_entry', models.DateField(blank=True, null=True)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.foodname')),
                ('mesure_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canadiannutrientfile.mesurename')),
            ],
            options={
                'unique_together': {('food_name', 'mesure_name')},
            },
        ),
    ]
