# Generated by Django 4.0.5 on 2023-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadiannutrientfile', '0002_nutrientname_nutrientsource_mesurename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodname',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
