# Generated by Django 4.0.5 on 2023-01-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadiannutrientfile', '0004_remove_foodname_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodname',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
